language: java
jdk:
- oraclejdk8
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAIJPHX7NGABEIUPFQ
  - secure: ON5tNJY2+YjFum/bhR2GnldRyatPoi9a0Mx9CbtN75lDuYOIqr/vK9gFwRaFLLu5Lb3x2dUifpbzun/unFtvhoq80/FaFYUOi7Z/6VHSoWW9w0wvmoi4p6zBg/8pFw8TG6AhGXy98BGrlJkmWo0PwUFQSmxXuXVG+FNa70LWoeJNhLu69Z9K8bF40mO0dpcU4Auk0JRcwUVKyvnFBZJ1XsgOVhekCHUM3DWe5qII1zRIoAvchpOHqMMKqJtL1np8wQJFjTRkDzaZEWs784C4cl/Ea43/8RyepoRyZWZ9lrEx1GuCNGJ0wNqTAmgu+Wjv/l4Jrcp9InabcnDyncV/HHRat3CiWuN3qiBBrgFFge6EQ18ptlFB+XZa6Pv1/q1UODVg1hwA4LimiedfDYMHz9GHbMAPp5YqVk3TY5sN3kNfx7GyC3qRfdKC544i1fyobRoIdc9E4N+R0loMLOQzycYLgrgeQKplMGWbIZJS6FJVm6/6C81g5SP9KL6N3yBGa5uJrXt7m6gGc0kFxqvMSEQkq2jjhUD8MOcjorX/4teJUsQeUOE4wTD3dwddDSfkf37BZf+NCQJTENuhqx5SWb45gHJsMX0yunufN5qZXDVfVY15kJOwPbX65eqDivpyYmxnt5/naZEBZztgV6XsQX3+qVJhUXQeWfTsSvNBGXM=
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
install:
- gradle buildZip
script:
- gradle buildZip
- "./upload.sh"
